name: Simple Heic To Jpg Converter

on:
  push:
    branches:
    - '**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build image
      run: docker build .